version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dish
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  job4j_dish:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
  environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/job4j_order
    - SPRING_DATASOURCE_USERNAME=compose-postgres
    - SPRING_DATASOURCE_PASSWORD=compose-postgres
    container_name: job4j_dish
    depends_on:
      - db