version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_USER=compose-postgres
      - POSTGRES_DB=dish
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dish
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    ports:
      - "127.0.0.1:8083:8083"
    depends_on:
      - db